### ISSUE TITLE
azure_rm_keyvaultsecret_info returns MSIAuthentication error when using managed identity

### ISSUE THREAD

**Issue by tze-dev** [ansible/ansible_collections_azure#1183]
##### SUMMARY

Later versions of azure.azcollection return 'MSIAuthentication' object has no attribute 'get_token' error when using manged identity.

This works with azcollection v1.13.0, but does not work with v1.14.0+

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`azure_rm_keyvaultsecret_info`

Suspecting this is a common issue across the board affecting more than one module.  Refer to this issue:
https://stackoverflow.com/questions/76155051/azure-msi-token-issue-when-applying-ansible-playbook-from-azure-cli

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.0]
  config file = None
  configured module search path = ['/home/azureuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /home/azureuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
azure.azcollection 1.16.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = None
```

##### OS / ENVIRONMENT

Ubuntu 22.04 running on Azure

##### STEPS TO REPRODUCE

Playbook: get-secret.yml

```yaml
---
- hosts: localhost
  collections:
    - azure.azcollection
  tasks:
    - name: Get secret
      azure_rm_keyvaultsecret_info:
        auth_source: msi
        vault_uri: https://somekeyvaultname.vault.azure.net
        name: kv-secret-name
      register: azure_secret

    - name: Show secret
      debug:
        var: azure_secret.secrets
```

Run playbook:

`ansible-playbook get-secret.yml`

##### EXPECTED RESULTS

Using `azcollection` version 1.13.0, it would return retrieve the secret value from Keyvault and return the result. 

##### ACTUAL RESULTS

```paste below
ansible-playbook [core 2.15.0]
  config file = None
  configured module search path = ['/azureuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /azureuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
No config file found; using defaults
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: azure.yml *********************************************************************************************************************************************************************************************
1 plays in azure.yml

PLAY [localhost] ************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************************************
task path: /home/azureuser/temp/azure.yml:2
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: azureuser
<127.0.0.1> EXEC /bin/sh -c 'echo ~azureuser && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /azureuser/.ansible/tmp `"&& mkdir "` echo /azureuser/.ansible/tmp/ansible-tmp-1686033631.3925037-9963-196063150114514 `" && echo ansible-tmp-1686033631.3925037-9963-196063150114514="` echo /azureuser/.ansible/tmp/ansible-tmp-1686033631.3925037-9963-196063150114514 `" ) && sleep 0'
Using module file /usr/local/lib/python3.10/dist-packages/ansible/modules/setup.py
<127.0.0.1> PUT /azureuser/.ansible/tmp/ansible-local-9958wzli94on/tmp1sk43zem TO /azureuser/.ansible/tmp/ansible-tmp-1686033631.3925037-9963-196063150114514/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /azureuser/.ansible/tmp/ansible-tmp-1686033631.3925037-9963-196063150114514/ /azureuser/.ansible/tmp/ansible-tmp-1686033631.3925037-9963-196063150114514/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /azureuser/.ansible/tmp/ansible-tmp-1686033631.3925037-9963-196063150114514/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /azureuser/.ansible/tmp/ansible-tmp-1686033631.3925037-9963-196063150114514/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [Get secret] ***********************************************************************************************************************************************************************************************
task path: /home/azureuser/temp/azure.yml:6
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: azureuser
<127.0.0.1> EXEC /bin/sh -c 'echo ~azureuser && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /azureuser/.ansible/tmp `"&& mkdir "` echo /azureuser/.ansible/tmp/ansible-tmp-1686033632.3353841-10038-79877281228039 `" && echo ansible-tmp-1686033632.3353841-10038-79877281228039="` echo /azureuser/.ansible/tmp/ansible-tmp-1686033632.3353841-10038-79877281228039 `" ) && sleep 0'
Using module file /azureuser/.ansible/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret_info.py
<127.0.0.1> PUT /azureuser/.ansible/tmp/ansible-local-9958wzli94on/tmpf_ol54d0 TO /azureuser/.ansible/tmp/ansible-tmp-1686033632.3353841-10038-79877281228039/AnsiballZ_azure_rm_keyvaultsecret_info.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /azureuser/.ansible/tmp/ansible-tmp-1686033632.3353841-10038-79877281228039/ /azureuser/.ansible/tmp/ansible-tmp-1686033632.3353841-10038-79877281228039/AnsiballZ_azure_rm_keyvaultsecret_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /azureuser/.ansible/tmp/ansible-tmp-1686033632.3353841-10038-79877281228039/AnsiballZ_azure_rm_keyvaultsecret_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /azureuser/.ansible/tmp/ansible-tmp-1686033632.3353841-10038-79877281228039/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_azure_rm_keyvaultsecret_info_payload_hiuz69zv/ansible_azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 1697, in _get_msi_credentials
    subscription = next(subscription_client.subscriptions.list())
  File "/usr/local/lib/python3.10/dist-packages/azure/core/paging.py", line 124, in __next__
    return next(self._page_iterator)
  File "/usr/local/lib/python3.10/dist-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/usr/local/lib/python3.10/dist-packages/azure/mgmt/resource/subscriptions/v2021_01_01/operations/_operations.py", line 431, in get_next
    pipeline_response = self._client._pipeline.run(  # pylint: disable=protected-access
  File "/usr/local/lib/python3.10/dist-packages/azure/core/pipeline/_base.py", line 202, in run
    return first_node.send(pipeline_request)
  File "/usr/local/lib/python3.10/dist-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.10/dist-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.10/dist-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.10/dist-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.10/dist-packages/azure/core/pipeline/policies/_redirect.py", line 156, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.10/dist-packages/azure/core/pipeline/policies/_retry.py", line 448, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.10/dist-packages/azure/core/pipeline/policies/_authentication.py", line 111, in send
    self.on_request(request)
  File "/usr/local/lib/python3.10/dist-packages/azure/core/pipeline/policies/_authentication.py", line 90, in on_request
    self._token = self._credential.get_token(*self._scopes)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "auth_source": "msi",
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "log_mode": null,
            "log_path": null,
            "name": "kv-secret-name",
            "password": null,
            "profile": null,
            "secret": null,
            "show_deleted_secret": false,
            "subscription_id": null,
            "tags": null,
            "tenant": null,
            "thumbprint": null,
            "vault_uri": "https://somekeyvaultname.vault.azure.net",
            "version": "current",
            "x509_certificate_path": null
        }
    },
    "msg": "Failed to get MSI token: 'MSIAuthentication' object has no attribute 'get_token'. Please check whether your machine enabled MSI or grant access to any subscription."
}
```

**Comment by riemers** [comment]
This also happens with the azure_rm inventory plugin when it tries to grab the subscription information. `ansible/staging/inventoryd3.azure_rm.yml with auto plugin: Failed to get MSI token: 'MSIAuthentication' object has no attribute 'get_token'. Please check whether your
machine enabled MSI or grant access to any subscription.`

Once i reverted to 1.13 the issue was gone and all was working again. Easy way to reproduce is to get a VM, make sure you can do a `az login --identity` and if that succeeds just run an inventory with anything higher then 1.13 to see the error message.

p.s. for the original author. If i set my subscription i don't get this error so perhaps if you set it on your task it also doesn't happen with newer version (but yes we want to see it fixed)

**Comment by Fred-sun** [comment]
@riemers Thanks for your question.  from your test logs. Machine did not add role assignment! Please enable System Assignment and add Azure Role Assignment! Thank you very much!

![285398311-210a88a5-89a5-4382-926b-9bd6bfb19f4a](https://github.com/ansible-collections/azure/assets/37327967/345f8e38-24fc-4625-8a78-6ec91d36d01b)

**Comment by riemers** [comment]
@Fred-sun  initial question  was not from me.  I do have system AND a role assignment. I mean older versions did work so i still believe this is a bug. (I do have system identity 100%)
