### PR TITLE
Fixed an error when client_id and secret are empty in kevault

### LINKED ISSUE #1183: azure_rm_keyvaultsecret_info returns MSIAuthentication error when using managed identity
##### SUMMARY

Later versions of azure.azcollection return 'MSIAuthentication' object has no attribute 'get_token' error when using manged identity.

This works with azcollection v1.13.0, but does not work with v1.14.0+

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`azure_rm_keyvaultsecret_info`

Suspecting this is a common issue across the board affecting more than one module.  Refer to this issue:
https://stackoverflow.com/questions/76155051/azure-msi-token-issue-when-applying-ansible-playbook-from-azure-cli

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.0]
  config file = None
  configured module search path = ['/home/azureuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /home/azureuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
azure.azcollection 1.16.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = None
```

##### OS / ENVIRONMENT

Ubuntu 22.04 running on Azure

##### STEPS TO REPRODUCE

Playbook: get-secret.yml

```yaml
---
- hosts: localhost
  collections:
    - azure.azcollection
  tasks:
    - name: Get secret
      azure_rm_keyvaultsecret_info:
        auth_source: msi
        vault_uri: https://somekeyvaultname.vault.azure.net
        name: kv-secret-name
      register: azure_secret

    - name: Show secret
      debug:
        var: azure_secret.secrets
```

Run playbook:

`ansible-playbook get-secret.yml`

##### EXPECTED RESULTS

Using `azcollection` version 1.13.0, it would return retrieve the secret value from Keyvault and return the result. 

##### ACTUAL RESULTS

```paste below
ansible-playbook [core 2.15.0]
  config file = None
  configured module search path = ['/azureuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /azureuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
No config file found; using defaults
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: azure.yml *********************************************************************************************************************************************************************************************
1 plays in azure.yml

PLAY [localhost] ************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************************************
task path: /home/azureuser/temp/azure.yml:2
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: azureuser
<127.0.0.1> EXEC /bin/sh -c 'echo ~azureuser && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /azureuser/.ansible/tmp `"&& mkdir "` echo /azureuser/.ansible/tmp/ansible-tmp-1686033631.3925037-9963-196063150114514 `" && echo ansible-tmp-1686033631.3925037-9963-196063150114514="` echo /azureuser/.ansible/tmp/ansible-tmp-1686033631.3925037-9963-196063150114514 `" ) && sleep 0'
Using module file /usr/local/lib/python3.10/dist-packages/ansible/modules/setup.py
<127.0.0.1> PUT /azureuser/.ansible/tmp/ansible-local-9958wzli94on/tmp1sk43zem TO /azureuser/.ansible/tmp/ansible-tmp-1686033631.3925037-9963-196063150114514/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /azureuser/.ansible/tmp/ansible-tmp-1686033631.3925037-9963-196063150114514/ /azureuser/.ansible/tmp/ansible-tmp-1686033631.3925037-9963-196063150114514/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /azureuser/.ansible/tmp/ansible-tmp-1686033631.3925037-9963-196063150114514/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /azureuser/.ansible/tmp/ansible-tmp-1686033631.3925037-9963-196063150114514/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [Get secret] ***********************************************************************************************************************************************************************************************
task path: /home/azureuser/temp/azure.yml:6
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: azureuser
<127.0.0.1> EXEC /bin/sh -c 'echo ~azureuser && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /azureuser/.ansible/tmp `"&& mkdir "` echo /azureuser/.ansible/tmp/ansible-tmp-1686033632.3353841-10038-79877281228039 `" && echo ansible-tmp-1686033632.3353841-10038-79877281228039="` echo /azureuser/.ansible/tmp/ansible-tmp-1686033632.3353841-10038-79877281228039 `" ) && sleep 0'
Using module file /azureuser/.ansible/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret_info.py
<127.0.0.1> PUT /azureuser/.ansible/tmp/ansible-local-9958wzli94on/tmpf_ol54d0 TO /azureuser/.ansible/tmp/ansible-tmp-1686033632.3353841-10038-79877281228039/AnsiballZ_azure_rm_keyvaultsecret_info.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /azureuser/.ansible/tmp/ansible-tmp-1686033632.3353841-10038-79877281228039/ /azureuser/.ansible/tmp/ansible-tmp-1686033632.3353841-10038-79877281228039/AnsiballZ_azure_rm_keyvaultsecret_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /azureuser/.ansible/tmp/ansible-tmp-1686033632.3353841-10038-79877281228039/AnsiballZ_azure_rm_keyvaultsecret_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /azureuser/.ansible/tmp/ansible-tmp-1686033632.3353841-10038-79877281228039/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_azure_rm_keyvaultsecret_info_payload_hiuz69zv/ansible_azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 1697, in _get_msi_credentials
    subscription = next(subscription_client.subscriptions.list())
  File "/usr/local/lib/python3.10/dist-packages/azure/core/paging.py", line 124, in __next__
    return next(self._page_iterator)
  File "/usr/local/lib/python3.10/dist-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/usr/local/lib/python3.10/dist-packages/azure/mgmt/resource/subscriptions/v2021_01_01/operations/_operations.py", line 431, in get_next
    pipeline_response = self._client._pipeline.run(  # pylint: disable=protected-access
  File "/usr/local/lib/python3.10/dist-packages/azure/core/pipeline/_base.py", line 202, in run
    return first_node.send(pipeline_request)
  File "/usr/local/lib/python3.10/dist-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.10/dist-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.10/dist-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.10/dist-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.10/dist-packages/azure/core/pipeline/policies/_redirect.py", line 156, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.10/dist-packages/azure/core/pipeline/policies/_retry.py", line 448, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.10/dist-packages/azure/core/pipeline/policies/_authentication.py", line 111, in send
    self.on_request(request)
  File "/usr/local/lib/python3.10/dist-packages/azure/core/pipeline/policies/_authentication.py", line 90, in on_request
    self._token = self._credential.get_token(*self._scopes)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "auth_source": "msi",
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "log_mode": null,
            "log_path": null,
            "name": "kv-secret-name",
            "password": null,
            "profile": null,
            "secret": null,
            "show_deleted_secret": false,
            "subscription_id": null,
            "tags": null,
            "tenant": null,
            "thumbprint": null,
            "vault_uri": "https://somekeyvaultname.vault.azure.net",
            "version": "current",
            "x509_certificate_path": null
        }
    },
    "msg": "Failed to get MSI token: 'MSIAuthentication' object has no attribute 'get_token'. Please check whether your machine enabled MSI or grant access to any subscription."
}
```

### LINKED ISSUE #1184: writing on azure keyvault returns error
##### SUMMARY
In 1.16.0 version writing values to azure keyvault is not working
Same steps do work in 1.15.0 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_keyvault

##### ANSIBLE VERSION

```
ansible [core 2.15.0]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /app/ansible-playbook/lib/python3.10/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = ansible-playbook/bin/ansible
  python version = 3.10.11 (main, May 11 2023, 23:59:31) [GCC 12.2.1 20220924] (/app/ansible-playbook/bin/python)
  jinja version = 3.1.2
  libyaml = False
```

##### COLLECTION VERSION

```
azure.azcollection            1.16.0 
```

##### OS / ENVIRONMENT

Docker image 
https://mcr.microsoft.com/en-us/product/azure-cli/about

##### STEPS TO REPRODUCE
you can reproduce following this tutorial:
https://learn.microsoft.com/en-us/azure/developer/ansible/key-vault-configure-secrets?tabs=ansible

step 1:
being logged in in Azure create a value in an existing keyvault with a playbook like this:

```yaml
---
- hosts: localhost
  connection: local

  tasks:

  - name: Get Key Vault by name
    azure_rm_keyvault_info:
      resource_group: ansible-kv-test-rg
      name: <vaultName>
    register: keyvault

  - name: set KeyVault uri fact
    set_fact: keyvaulturi="{{ keyvault['keyvaults'][0]['vault_uri'] }}"

  - name: Create a secret
    azure_rm_keyvaultsecret:
      secret_name: adminPassword
      secret_value: <secretValue>
      keyvault_uri: "{{ keyvaulturi }}"

```
apply the playbook 

`ansible-playbook create_kv_secret.yml`

##### EXPECTED RESULTS
Value is updated on the keyvault

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'client_id'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1686057345.3356755-215-125516659736374/AnsiballZ_azure_rm_keyvaultsecret.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1686057345.3356755-215-125516659736374/AnsiballZ_azure_rm_keyvaultsecret.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1686057345.3356755-215-125516659736374/AnsiballZ_azure_rm_keyvaultsecret.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_keyvaultsecret', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_keyvaultsecret', _modlib_path=modlib_path),\n  File \"/usr/local/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_0ajg29u_/ansible_azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret.py\", line 271, in <module>\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_0ajg29u_/ansible_azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret.py\", line 267, in main\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_0ajg29u_/ansible_azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret.py\", line 140, in __init__\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_0ajg29u_/ansible_azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 472, in __init__\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_0ajg29u_/ansible_azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret.py\", line 151, in exec_module\n  File \"/tmp/ansible_azure_rm_keyvaultsecret_payload_0ajg29u_/ansible_azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret.py\", line 212, in get_keyvault_client\nKeyError: 'client_id'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

```

### PR DESCRIPTION
**Pull request by Fred-sun**
##### SUMMARY

Fixed an error when client_id and secret are empty in kevault, try to fix #1184

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

azure_rm_keyvaultkey.py
azure_rm_keyvaultkey_info.py
azure_rm_keyvaultsecret.py
azure_rm_keyvaultsecret_info.py
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by xuzhang3 — APPROVED** [review]

**Comment by xuzhang3** [comment]
LGTM
