### ISSUE TITLE
`azure_rm_keyvaultsecret_info`: Session.request() fails with unexpected keyword argument 'enable_cae'

### ISSUE THREAD

**Issue by jpsullivan** [ansible/ansible_collections_azure#1780]
##### SUMMARY
When attempting to fetch secrets from Azure Key Vault using the `azure_rm_keyvaultsecret_info` module, the task fails with an error indicating an unexpected keyword argument `enable_cae` in the Session.request() call.

```
failed: [...] => {
    "msg": "Find the key vault secret got exception, exception as Session.request() got an unexpected keyword argument 'enable_cae'"
}
```

I'm aware that this has been identified in other repos (https://github.com/Azure/azure-cli/issues/27131) and allegedly patched, but this appears to still be an issue with `azcollection`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`azure_rm_keyvaultsecret_info`

##### ANSIBLE VERSION

```paste below
ansible [core 2.18.1]
  config file = /Users/{omitted}/ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/.local/lib/python3.13/site-packages/ansible
  ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
  executable location = ~/.local/bin/ansible
  python version = 3.13.1 (main, Dec  6 2024, 23:51:49) [Clang 16.0.0 (clang-1600.0.26.4)] (~/.pyenv/versions/3.13.1/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```paste below
3.1.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = ~/{omitted}/ansible.cfg
DEFAULT_HOST_LIST(~/{omitted}/ansible.cfg) = ['~/{omitted}/inventory.yml']
DEFAULT_REMOTE_USER(~/{omitted}/ansible.cfg) = pi
DEFAULT_ROLES_PATH(~/{omitted}/ansible.cfg) = ['~/{omitted}/roles']
DEFAULT_TIMEOUT(~/{omitted}/ansible.cfg) = 60
HOST_KEY_CHECKING(~/{omitted}/ansible.cfg) = False
```

##### OS / ENVIRONMENT

OS: macos 15.1.1 (24B91)

##### STEPS TO REPRODUCE

1. Install all ansible and python requirements:
```bash
ansible-galaxy collection install -r requirements.yml
pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements.txt
```

2. Create and execute an Ansible playbook with the following task:
```yaml
- name: Get secrets from Azure Key Vault
  azure.azcollection.azure_rm_keyvaultsecret_info:
    vault_uri: "https://[keyvault-name].vault.azure.net"
    name: "{{ item.name }}"
  register: "secret_result"
  loop: "{{ keyvault_secrets }}"
```

##### EXPECTED RESULTS

Expected to pull the secrets that I am sure exist within my KeyVault.

##### ACTUAL RESULTS

Pasted the relevant exception details below:

```paste below
Using module file ~/.ansible/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret_info.py
<localhost> PUT ~/.ansible/tmp/ansible-local-40316fj6yt8xi/tmpuzkbh3pf TO ~/.ansible/tmp/ansible-tmp-1733580995.382248-40495-202277196457352/AnsiballZ_azure_rm_keyvaultsecret_info.py
<localhost> EXEC /bin/sh -c 'chmod u+x ~/.ansible/tmp/ansible-tmp-1733580995.382248-40495-202277196457352/ ~/.ansible/tmp/ansible-tmp-1733580995.382248-40495-202277196457352/AnsiballZ_azure_rm_keyvaultsecret_info.py && sleep 0'
<localhost> EXEC /bin/sh -c '~/.pyenv/versions/3.13.1/bin/python3 ~/.ansible/tmp/ansible-tmp-1733580995.382248-40495-202277196457352/AnsiballZ_azure_rm_keyvaultsecret_info.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r ~/.ansible/tmp/ansible-tmp-1733580995.382248-40495-202277196457352/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/var/folders/h8/bm4d0tb515gc29t8xq_zkn8r0000gn/T/ansible_azure.azcollection.azure_rm_keyvaultsecret_info_payload_n34rhpb2/ansible_azure.azcollection.azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret_info.py", line 297, in get_secret
    response = self._client.get_secret(name=self.name, version='')
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/azure/keyvault/secrets/_client.py", line 65, in get_secret
    bundle = self._client.get_secret(
        vault_base_url=self._vault_url,
    ...<2 lines>...
        **kwargs
    )
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/azure/keyvault/secrets/_generated/_operations/_operations.py", line 751, in get_secret
    pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        _request, stream=_stream, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/azure/core/pipeline/_base.py", line 229, in run
    return first_node.send(pipeline_request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/azure/core/pipeline/policies/_redirect.py", line 197, in send
    response = self.next.send(request)
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/azure/core/pipeline/policies/_retry.py", line 532, in send
    response = self.next.send(request)
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/azure/keyvault/secrets/_shared/challenge_auth_policy.py", line 120, in send
    return self.handle_challenge_flow(request, response)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/azure/keyvault/secrets/_shared/challenge_auth_policy.py", line 149, in handle_challenge_flow
    request_authorized = self.on_challenge(request, response)
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/azure/keyvault/secrets/_shared/challenge_auth_policy.py", line 239, in on_challenge
    self.authorize_request(request, scope, claims=challenge.claims, tenant_id=challenge.tenant_id)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/azure/core/pipeline/policies/_authentication.py", line 133, in authorize_request
    self._request_token(*scopes, **kwargs)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/azure/core/pipeline/policies/_authentication.py", line 96, in _request_token
    self._token = cast(TokenCredential, self._credential).get_token(*scopes, **kwargs)
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/azure/cli/core/auth/credential_adaptor.py", line 65, in get_token
    token, _ = self._get_token(scopes, **kwargs)
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/azure/cli/core/auth/credential_adaptor.py", line 38, in _get_token
    token = self._credential.get_token(*scopes, **kwargs)
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/azure/cli/core/auth/msal_authentication.py", line 69, in get_token
    result = self.acquire_token_silent_with_error(list(scopes), self._account, claims_challenge=claims, **kwargs)
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/msal/application.py", line 1401, in acquire_token_silent_with_error
    return _clean_up(self._acquire_token_silent_with_error(
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        scopes, account, authority=authority, force_refresh=force_refresh,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        claims_challenge=claims_challenge, auth_scheme=auth_scheme, **kwargs))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/msal/application.py", line 1424, in _acquire_token_silent_with_error
    result = self._acquire_token_silent_from_cache_and_possibly_refresh_it(
        scopes, account, self.authority, force_refresh=force_refresh,
    ...<2 lines>...
        auth_scheme=auth_scheme,
        **kwargs)
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/msal/application.py", line 1559, in _acquire_token_silent_from_cache_and_possibly_refresh_it
    result = self._acquire_token_silent_by_finding_rt_belongs_to_me_or_my_family(
        authority, self._decorate_scope(scopes), account,
        refresh_reason=refresh_reason, claims_challenge=claims_challenge,
        correlation_id=correlation_id,
        **kwargs)
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/msal/application.py", line 1620, in _acquire_token_silent_by_finding_rt_belongs_to_me_or_my_family
    last_resp = at = self._acquire_token_silent_by_finding_specific_refresh_token(
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        authority, scopes, dict(query, family_id=app_metadata["family_id"]),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        **kwargs)
        ^^^^^^^^^
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/msal/application.py", line 1668, in _acquire_token_silent_by_finding_specific_refresh_token
    response = client.obtain_token_by_refresh_token(
        entry, rt_getter=lambda token_item: token_item["secret"],
    ...<13 lines>...
                self._client_capabilities, claims_challenge)),
        **kwargs)
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/msal/oauth2cli/oauth2.py", line 835, in obtain_token_by_refresh_token
    resp = super(Client, self).obtain_token_by_refresh_token(
        rt_getter(token_item)
    ...<2 lines>...
        also_save_rt=on_updating_rt is False,
        **kwargs)
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/msal/oauth2cli/oauth2.py", line 265, in obtain_token_by_refresh_token
    return self._obtain_token("refresh_token", data=data, **kwargs)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/msal/oauth2cli/oidc.py", line 170, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/msal/oauth2cli/oauth2.py", line 776, in _obtain_token
    resp = super(Client, self)._obtain_token(
        grant_type, params, _data, *args, **kwargs)
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/msal/oauth2cli/oauth2.py", line 237, in _obtain_token
    resp = (post or self._http_client.post)(
        self.configuration["token_endpoint"],
        headers=_headers, params=params, data=_data,
        **kwargs)
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/msal/individual_cache.py", line 269, in wrapper
    value = function(*args, **kwargs)
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/msal/individual_cache.py", line 269, in wrapper
    value = function(*args, **kwargs)
  File "~/.pyenv/versions/3.13.1/lib/python3.13/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
failed: [devbox -> localhost] (item={'name': '{my_secret_name}', 'variable_name': '{my_secret_variable_name}'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "auth_source": "auto",
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "disable_instance_discovery": false,
            "log_mode": null,
            "log_path": null,
            "name": "{my_secret_name}",
            "password": null,
            "profile": null,
            "secret": null,
            "show_deleted_secret": false,
            "subscription_id": null,
            "tags": null,
            "tenant": null,
            "thumbprint": null,
            "vault_uri": "{my_kv_uri}",
            "version": "current",
            "x509_certificate_path": null
        }
    },
    "item": {
        "name": "{my_secret_name}",
        "variable_name": "{my_secret_variable_name}"
    },
    "msg": "Find the key vault secret got exception, exception as Session.request() got an unexpected keyword argument 'enable_cae'"
}
```

**Comment by Fred-sun** [comment]
@jpsullivan Which authentication method do you use? For example, credentials files, environment variables or 'az login', thank you!

**Comment by jpsullivan** [comment]
Hey @Fred-sun! Thanks for taking a look. 

I typically use az login to authenticate.

**Comment by SrinivasanSelvam** [comment]
Facing same issue with ansible version 
ansible [core 2.17.4]
azure cli version - 2.66.0*

Facing issue with azure.azcollection.azure_rm_keyvaultsecret_info ansible module 
azure.azcollection.azure_keyvault_secret ansible module is working as of now

**Comment by Fred-sun** [comment]
@jpsullivan Could you please provide the `pip3 list` information? More conducive to solving the current problem, thank you!

**Comment by Fred-sun** [comment]
@jpsullivan In addition, please provide the version of `azure.azcollection`, thank you!
```
 ansible-galaxy collection list|grep 'azure.azcollection'

**Comment by zbenamram** [comment]
@Fred-sun - I'm experiencing the same issue for azure.azcollection 3.1.0

**Comment by Fred-sun** [comment]
@zbenamram Could you please provide the pip3 list information? More conducive to solving the current problem, thank you!

**Comment by zbenamram** [comment]
@Fred-sun - no problem. Thanks so much for taking a look

```
pip3 list

Package                                 Version
--------------------------------------- -----------
adal                                    1.2.7
aiohappyeyeballs                        2.4.4
aiohttp                                 3.11.10
aiosignal                               1.3.2
ansible                                 11.1.0
ansible-core                            2.18.1
anyio                                   4.7.0
applicationinsights                     0.11.10
argcomplete                             3.3.0
attrs                                   24.3.0
azure-cli-core                          2.64.0
azure-cli-telemetry                     1.1.0
azure-common                            1.1.28
azure-containerregistry                 1.2.0
azure-core                              1.31.0
azure-identity                          1.19.0
azure-keyvault                          4.2.0
azure-keyvault-certificates             4.9.0
azure-keyvault-keys                     4.10.0
azure-keyvault-secrets                  4.9.0
azure-mgmt-apimanagement                4.0.1
azure-mgmt-authorization                4.0.0
azure-mgmt-automation                   1.1.0b4
azure-mgmt-batch                        17.3.0
azure-mgmt-cdn                          13.1.1
azure-mgmt-compute                      33.0.0
azure-mgmt-containerinstance            10.1.0
azure-mgmt-containerregistry            10.3.0
azure-mgmt-containerservice             32.1.0
azure-mgmt-core                         1.4.0
azure-mgmt-cosmosdb                     10.0.0b3
azure-mgmt-datafactory                  9.0.0
azure-mgmt-devtestlabs                  10.0.0b2
azure-mgmt-dns                          8.1.0
azure-mgmt-eventhub                     11.1.0
azure-mgmt-hdinsight                    9.1.0b1
azure-mgmt-iothub                       3.0.0
azure-mgmt-keyvault                     10.3.1
azure-mgmt-loganalytics                 13.0.0b7
azure-mgmt-managedservices              7.0.0b2
azure-mgmt-managementgroups             1.1.0b2
azure-mgmt-marketplaceordering          1.2.0b2
azure-mgmt-monitor                      6.0.2
azure-mgmt-network                      28.0.0
azure-mgmt-notificationhubs             8.1.0b1
azure-mgmt-nspkg                        3.0.2
azure-mgmt-privatedns                   1.1.0
azure-mgmt-rdbms                        10.2.0b17
azure-mgmt-recoveryservices             3.0.0
azure-mgmt-recoveryservicesbackup       9.1.0
azure-mgmt-redis                        14.4.0
azure-mgmt-resource                     23.2.0
azure-mgmt-search                       9.2.0b2
azure-mgmt-servicebus                   8.2.1
azure-mgmt-sql                          4.0.0b19
azure-mgmt-storage                      21.2.1
azure-mgmt-trafficmanager               1.1.0
azure-mgmt-web                          7.3.1
azure-nspkg                             3.0.2
azure-storage-blob                      12.23.0b1
bcrypt                                  4.2.1
certifi                                 2024.12.14
cffi                                    1.17.1
charset-normalizer                      3.4.0
cryptography                            44.0.0
Deprecated                              1.2.15
frozenlist                              1.5.0
h11                                     0.14.0
h2                                      4.1.0
hpack                                   4.0.0
httpcore                                1.0.7
httpx                                   0.28.1
humanfriendly                           10.0
hyperframe                              6.0.1
idna                                    3.10
importlib_metadata                      8.5.0
isodate                                 0.7.2
Jinja2                                  3.1.4
jmespath                                1.0.1
knack                                   0.11.0
MarkupSafe                              3.0.2
microsoft-kiota-abstractions            1.6.7
microsoft-kiota-authentication-azure    1.6.7
microsoft-kiota-http                    1.6.7
microsoft-kiota-serialization-form      1.6.7
microsoft-kiota-serialization-json      1.6.7
microsoft-kiota-serialization-multipart 1.6.7
microsoft-kiota-serialization-text      1.6.7
msal                                    1.30.0
msal-extensions                         1.2.0
msgraph-core                            1.1.7
msgraph-sdk                             1.6.0
msrest                                  0.7.1
msrestazure                             0.6.4.post1
multidict                               6.1.0
oauthlib                                3.2.2
opentelemetry-api                       1.29.0
opentelemetry-sdk                       1.29.0
opentelemetry-semantic-conventions      0.50b0
packaging                               24.2
paramiko                                3.5.0
pendulum                                3.0.0
pip                                     24.2
pkginfo                                 1.12.0
portalocker                             2.10.1
propcache                               0.2.1
psutil                                  6.1.0
pycparser                               2.22
Pygments                                2.18.0
PyJWT                                   2.10.1
PyNaCl                                  1.5.0
pyOpenSSL                               24.3.0
PySocks                                 1.7.1
python-dateutil                         2.9.0.post0
PyYAML                                  6.0.2
requests                                2.32.3
requests-oauthlib                       2.0.0
resolvelib                              1.0.1
six                                     1.17.0
sniffio                                 1.3.1
std-uritemplate                         2.0.1
tabulate                                0.9.0
time-machine                            2.16.0
typing_extensions                       4.12.2
tzdata                                  2024.2
urllib3                                 2.2.3
wrapt                                   1.17.0
xmltodict                               0.14.2
yarl                                    1.18.3
zipp                                    3.21.0
```

**Comment by Fred-sun** [comment]
@jpsullivan @zbenamram It was a strange question because I couldn't reproduce it locally.   Is likely to be caused by `azure - core`, refer to connect (https://github.com/Azure/azure-cli/issues/27131), which is likely to be your azure CLI version of environment problems.   Can you switch versions to try?   Or create a new virtual to try, thanks!

**Comment by phire-tc** [comment]
I can work around this crash by downgrading to `azure-keyvault-secrets==4.8.0`. Version 4.9.0 added the `enable_cae=True` kwarg but evidently not all of the code in the stack can handle it.

**Comment by phire-tc** [comment]
The bug appears to be here: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/challenge_auth_policy.py#L91-L92

**Comment by jpsullivan** [comment]
Hey @Fred-sun, apologies for the delay. Here's the info you requested:

```
$ pip3 list

Package                                 Version
--------------------------------------- -----------
adal                                    1.2.7
aiohappyeyeballs                        2.4.4
aiohttp                                 3.11.10
aiosignal                               1.3.1
ansible                                 11.1.0
ansible-core                            2.18.1
anyio                                   4.7.0
applicationinsights                     0.11.10
argcomplete                             3.3.0
attrs                                   24.2.0
azure-cli-core                          2.64.0
azure-cli-telemetry                     1.1.0
azure-common                            1.1.28
azure-containerregistry                 1.2.0
azure-core                              1.31.0
azure-identity                          1.19.0
azure-keyvault                          4.2.0
azure-keyvault-certificates             4.9.0
azure-keyvault-keys                     4.10.0
azure-keyvault-secrets                  4.9.0
azure-mgmt-apimanagement                4.0.1
azure-mgmt-authorization                4.0.0
azure-mgmt-automation                   1.1.0b4
azure-mgmt-batch                        17.3.0
azure-mgmt-cdn                          13.1.1
azure-mgmt-compute                      33.0.0
azure-mgmt-containerinstance            10.1.0
azure-mgmt-containerregistry            10.3.0
azure-mgmt-containerservice             32.1.0
azure-mgmt-core                         1.4.0
azure-mgmt-cosmosdb                     10.0.0b3
azure-mgmt-datafactory                  9.0.0
azure-mgmt-devtestlabs                  10.0.0b2
azure-mgmt-dns                          8.1.0
azure-mgmt-eventhub                     11.1.0
azure-mgmt-hdinsight                    9.1.0b1
azure-mgmt-iothub                       3.0.0
azure-mgmt-keyvault                     10.3.1
azure-mgmt-loganalytics                 13.0.0b7
azure-mgmt-managedservices              7.0.0b2
azure-mgmt-managementgroups             1.1.0b2
azure-mgmt-marketplaceordering          1.2.0b2
azure-mgmt-monitor                      6.0.2
azure-mgmt-network                      28.0.0
azure-mgmt-notificationhubs             8.1.0b1
azure-mgmt-nspkg                        3.0.2
azure-mgmt-privatedns                   1.1.0
azure-mgmt-rdbms                        10.2.0b17
azure-mgmt-recoveryservices             3.0.0
azure-mgmt-recoveryservicesbackup       9.1.0
azure-mgmt-redis                        14.4.0
azure-mgmt-resource                     23.2.0
azure-mgmt-search                       9.2.0b2
azure-mgmt-servicebus                   8.2.1
azure-mgmt-sql                          4.0.0b19
azure-mgmt-storage                      21.2.1
azure-mgmt-trafficmanager               1.1.0
azure-mgmt-web                          7.3.1
azure-nspkg                             3.0.2
azure-storage-blob                      12.23.0b1
bcrypt                                  4.2.1
certifi                                 2024.8.30
cffi                                    1.17.1
charset-normalizer                      3.4.0
cryptography                            44.0.0
Deprecated                              1.2.15
frozenlist                              1.5.0
h11                                     0.14.0
h2                                      4.1.0
hpack                                   4.0.0
httpcore                                1.0.7
httpx                                   0.28.1
humanfriendly                           10.0
hyperframe                              6.0.1
idna                                    3.10
importlib_metadata                      8.5.0
isodate                                 0.7.2
Jinja2                                  3.1.4
jmespath                                1.0.1
knack                                   0.11.0
MarkupSafe                              3.0.2
microsoft-kiota-abstractions            1.6.6
microsoft-kiota-authentication-azure    1.6.6
microsoft-kiota-http                    1.6.6
microsoft-kiota-serialization-form      1.6.6
microsoft-kiota-serialization-json      1.6.6
microsoft-kiota-serialization-multipart 1.6.6
microsoft-kiota-serialization-text      1.6.6
msal                                    1.30.0
msal-extensions                         1.2.0
msgraph-core                            1.1.7
msgraph-sdk                             1.6.0
msrest                                  0.7.1
msrestazure                             0.6.4.post1
multidict                               6.1.0
oauthlib                                3.2.2
opentelemetry-api                       1.28.2
opentelemetry-sdk                       1.28.2
opentelemetry-semantic-conventions      0.49b2
packaging                               24.2
paramiko                                3.5.0
pendulum                                3.0.0
pip                                     24.3.1
pkginfo                                 1.12.0
portalocker                             2.10.1
propcache                               0.2.1
psutil                                  6.1.0
pycparser                               2.22
Pygments                                2.18.0
PyJWT                                   2.10.1
PyNaCl                                  1.5.0
pyOpenSSL                               24.3.0
PySocks                                 1.7.1
python-dateutil                         2.9.0.post0
PyYAML                                  6.0.2
requests                                2.32.3
requests-oauthlib                       2.0.0
resolvelib                              1.0.1
six                                     1.17.0
sniffio                                 1.3.1
std-uritemplate                         2.0.1
tabulate                                0.9.0
time-machine                            2.16.0
typing_extensions                       4.12.2
tzdata                                  2024.2
urllib3                                 2.2.3
wrapt                                   1.17.0
xmltodict                               0.14.2
yarl                                    1.18.3
zipp                                    3.21.0
```

```
$ ansible-galaxy collection list|grep 'azure.azcollection'
azure.azcollection                       3.1.0
azure.azcollection                       3.1.0
```

No clue why I've got two `azure.azcollection` entries though.

**Comment by Fred-sun** [comment]
@jpsullivan Can you try scaling down the `azure-keyvault-secrets` version as described in the comments above? Thank you!

**Comment by satanasdiabolo** [comment]
Hey there,
I'm having the same issue in my DevContainer. It was working fine with azcollection 3.1.0. Downgrading azure-keyvault-secrets to 4.8.0 allowed me to make it works again.

**Comment by phire-tc** [comment]
Hi @Fred-sun , I'm curious why you added the "not a bug" label. This is very much a bug.

**Comment by Fred-sun** [comment]
@jpsullivan This problem is strange because I have not had any problems installing it locally. I will consider a `not bug` label first and then retest the problem. Thank you!

**Comment by phire-tc** [comment]
Hi @Fred-sun - I've found that the bug doesn't surface when I'm using msi so to repro you'll want to try with login authentication.

**Comment by FireDrunk** [comment]
I'm running into the same issue, downgrading azure-keyvault-secrets to 4.8.0 (from 4.9.0) works.

**Comment by dt-andrews** [comment]
Got the same bug, how do I downgrade azure-keyvault-secrets?

**Comment by Fred-sun** [comment]
@dt-andrews Can you provide the azure. azcollection version and the '*keyvault* related version information in the environment(pip3 list |grep 'keyvault')?
 Also, as mentioned above, downgrade the 'azure-keyvault-secrets' version to v4.8.0 solves this problem.  Have you tried?

**Comment by dt-andrews** [comment]
Yes, I eventually figured out how to downgrade and that solved the problem.

```bash
:/mnt/c/Windows/System32$ ansible-galaxy collection list azure.azcollection

# /home/andrewsu/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 3.3.1

:/mnt/c/Windows/System32$ pip3 list |grep 'keyvault'
azure-keyvault                          4.2.0
azure-keyvault-certificates             4.9.0
azure-keyvault-keys                     4.10.0
azure-keyvault-secrets                  4.8.0
azure-mgmt-keyvault                     10.3.1
```

I've been installing ansible using:

```bash
# 1. Upgrade packages
sudo apt update
sudo apt upgrade

# 2. Install wslu - Windows Subsystem for Linux (WSL) utilities, specifically the ability to open browser in windows during az login. 
sudo apt update
sudo apt install wslu
echo 'export BROWSER=wslview' >> ~/.bashrc
source ~/.bashrc

# 3. Install Azure CLI
# Download and install the Microsoft signing key:
curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc.gpg > /dev/null

# Add the Azure CLI software repository:
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/azure-cli.list

sudo apt update
sudo apt install azure-cli

# 4. Install Ansible
sudo apt update
sudo apt install python3-pip
pip3 install ansible --break-system-packages

# 5. Install the Azure collection requirements:
ansible-galaxy collection list azure.azcollection
ansible-galaxy collection install azure.azcollection --upgrade
pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements.txt --break-system-packages
# Hit this bug <https://github.com/ansible-collections/azure/issues/1780#issuecomment-2575776294>, only work around is to downgrade azure-keyvault-secrets to 4.8.0
pip3 install azure-keyvault-secrets==4.8.0 --break-system-packages
```

**Comment by klandell** [comment]
> [@dt-andrews](https://github.com/dt-andrews) Can you provide the azure. azcollection version and the '_keyvault_ related version information in the environment(pip3 list |grep 'keyvault')? Also, as mentioned above, downgrade the 'azure-keyvault-secrets' version to v4.8.0 solves this problem. Have you tried?

I am having this exact issue. Strangely, yesterday I had no issues, and today I had to downgrade to 4.8.0. I would not call downgrading "Solving" the problem though.

Edit: I don't know what version I was on yesterday. Presumably I updated something unintentionally.

**Comment by p3ck** [comment]
I'm getting this error and it also works if I roll back 4.8.0

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Find the key vault secret got exception, exception as request() got an unexpected keyword argument 'claims'"}

```

**Comment by MallocArray** [comment]
Same issue after upgrading collection from 2.7.0 to 3.3.1 which also needed pip3 modules upgraded
azure-keyvault-secrets from 4.7.0 to 4.9.0

`FAILED! => {"changed": false, "msg": "Find the key vault secret got exception, exception as Session.request() got an unexpected keyword argument 'enable_cae'"}`

Relevant task after authenticating with `az login -u username@domain.com` or AWX using Azure Resource Manager for service principal:

```
- name: Get {{ controller_password_secret }} from Azure Key Vault secret
  azure.azcollection.azure_rm_keyvaultsecret_info:
    name: "{{ controller_password_secret }}"
    vault_uri: "{{ controller_password_vault | default('https://myvault.vault.azure.net') }}"
  # no_log: true
  delegate_to: localhost
  register: controller_password_secret
  tags:
    - password
    - always
```

As other users mentioned, downgrading azure-keyvault-secrets to 4.8.0 and keeping everything else on the newer versions allows me to retrieve the secrets, but that isn't the ideal solution

**Comment by Fred-sun** [comment]
Because I repeatedly simulated locally and didn't encounter this error. If it is determined to be related ‘to azure-keyvault-secret’, you can consider specifying the version of azure-keyvault-secret in requirements.txt. Thank you!

**Comment by MallocArray** [comment]
I can certainly address it by specifying `azure-keyvault-secrets==4.8.0` and then I no longer have the issue

I'm not sure why you aren't able to recreate the error, but with multiple people, it appears to be a legit issue.
Does my code snippet offer any insight, or need anything from my EE configuration?

**Comment by Fred-sun** [comment]
@MallocArray Perhaps I missed something. Could you provide the detailed information of vvv? Thank you!

**Comment by MallocArray** [comment]
At this point I am not doing any special workarounds with pinned versions and things are working with current collection versions, so I think this can be closed.

**Comment by zunyangc** [comment]
Closing this issue now, feel free to reopen if related issue appears.

Thanks!
