### ISSUE TITLE
'Cloud' object has no attribute 'decode'

### ISSUE THREAD

**Issue by nilleb** [ansible/ansible_collections_azure#1343]
##### SUMMARY

The azure collection 2.0.0 fails at logging in.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
8.6.1
ansible-core-2.15.6
```

##### COLLECTION VERSION

```paste below
2.0.0
```
it works on 1.19.0!

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

macos, python3.1

##### STEPS TO REPRODUCE

(any azure_rm_*_info will do)
```yaml
---
- name: verify key vault
  hosts: localhost
  gather_facts: false
  vars_files:
  - vars.yml
  vars:
    name: "key-vault-20231121.20"
    temp: "{{ name | hash('sha1') }}"
    kv_name: "{{ temp[:6] }}"
  tasks:

  - name: debug
    ansible.builtin.debug:
      var: kv_name

  - set_fact:
     name: "{{ kv_name }}"

  - name: gather facts
    azure_rm_keyvault_info:
      resource_group: "rg-{{ kv_name }}"
      name: "{{ vars.name }}"
    register: key_vault
```

##### EXPECTED RESULTS

The playbook does not raise an exception.

##### ACTUAL RESULTS

The script generates an exception.

```paste below
Traceback (most recent call last):
  File "/Users/nilleb/.ansible/tmp/ansible-tmp-1700584944.558722-56109-90814551627635/AnsiballZ_azure_rm_resourcegroup_info.py", line 107, in <module>
    _ansiballz_main()
  File "/Users/nilleb/.ansible/tmp/ansible-tmp-1700584944.558722-56109-90814551627635/AnsiballZ_azure_rm_resourcegroup_info.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/nilleb/.ansible/tmp/ansible-tmp-1700584944.558722-56109-90814551627635/AnsiballZ_azure_rm_resourcegroup_info.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_resourcegroup_info', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_resourcegroup_info', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/var/folders/55/3fj_pz0504z72ml1p4gh593c0000gn/T/ansible_azure_rm_resourcegroup_info_payload_vqyxovcd/ansible_azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup_info.py", line 238, in <module>
  File "/var/folders/55/3fj_pz0504z72ml1p4gh593c0000gn/T/ansible_azure_rm_resourcegroup_info_payload_vqyxovcd/ansible_azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup_info.py", line 234, in main
  File "/var/folders/55/3fj_pz0504z72ml1p4gh593c0000gn/T/ansible_azure_rm_resourcegroup_info_payload_vqyxovcd/ansible_azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup_info.py", line 163, in __init__
  File "/var/folders/55/3fj_pz0504z72ml1p4gh593c0000gn/T/ansible_azure_rm_resourcegroup_info_payload_vqyxovcd/ansible_azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 439, in __init__
  File "/var/folders/55/3fj_pz0504z72ml1p4gh593c0000gn/T/ansible_azure_rm_resourcegroup_info_payload_vqyxovcd/ansible_azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 1440, in __init__
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/parse.py", line 394, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/parse.py", line 133, in _coerce_args
    return _decode_args(args) + (_encode_result,)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/parse.py", line 117, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/parse.py", line 117, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
                 ^^^^^^^^
AttributeError: 'Cloud' object has no attribute 'decode'
```

**Comment by mschurenko** [comment]
I'm having the same issue with `2.0.0`

**Comment by Fred-sun** [comment]
@nilleb @mschurenko This issue is similar to #1339 and has been fixed by #1340!

**Comment by Timothy-Pulliam** [comment]
I see it is merged in dev branch. Has this been merged into a new tagged release?

**Comment by Fred-sun** [comment]
@Timothy-Pulliam Yes, we are ready to release a new version recently!
