### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'credential' on version 1.12.0

### ISSUE THREAD

**Issue by ToxicGLaDOS** [ansible/ansible_collections_azure#787]
##### SUMMARY

Since version 1.12.0 when we use `azure_rm_networkinterface_info` we get the following error:

```
TypeError: __init__() got an unexpected keyword argument 'credential'
```

I have tested and confirmed that the issue does not appear in 1.11.0.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`azure_rm_networkinterface_info`

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.3.post0] 
  config file = /ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
azure.azcollection 1.12.0 
```

##### OS / ENVIRONMENT

We see the issue in both AWX and our Redhat docker container which is built off of the [quay.io:0.6.0](https://quay.io/repository/ansible/awx-ee?tab=tags&tag=0.6.0) container.

##### STEPS TO REPRODUCE

```yaml
- name: Query azure nic
  azure_rm_networkinterface_info:
    resource_group: "{{ hostvars[inventory_hostname]['resource_group'] }}"
    name: "{{ hostvars[inventory_hostname]['network_interface'] }}"
  delegate_to: localhost
```

##### EXPECTED RESULTS

`azure_rm_networkinterface_info` returns the network interface information

##### ACTUAL RESULTS

```paste below
Traceback (most recent call last):
  File \"/home/runner/.ansible/tmp/ansible-tmp-1647624334.3959389-527-36480137061122/AnsiballZ_azure_rm_networkinterface_info.py\", line 100, in <module>
    _ansiballz_main()
  File \"/home/runner/.ansible/tmp/ansible-tmp-1647624334.3959389-527-36480137061122/AnsiballZ_azure_rm_networkinterface_info.py\", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/home/runner/.ansible/tmp/ansible-tmp-1647624334.3959389-527-36480137061122/AnsiballZ_azure_rm_networkinterface_info.py\", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_networkinterface_info', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_networkinterface_info', _modlib_path=modlib_path),
  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code
    exec(code, run_globals)
  File \"/tmp/ansible_azure_rm_networkinterface_info_payload_98gpx7ge/ansible_azure_rm_networkinterface_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_networkinterface_info.py\", line 356, in <module>
  File \"/tmp/ansible_azure_rm_networkinterface_info_payload_98gpx7ge/ansible_azure_rm_networkinterface_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_networkinterface_info.py\", line 352, in main
  File \"/tmp/ansible_azure_rm_networkinterface_info_payload_98gpx7ge/ansible_azure_rm_networkinterface_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_networkinterface_info.py\", line 283, in __init__
  File \"/tmp/ansible_azure_rm_networkinterface_info_payload_98gpx7ge/ansible_azure_rm_networkinterface_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 465, in __init__
  File \"/tmp/ansible_azure_rm_networkinterface_info_payload_98gpx7ge/ansible_azure_rm_networkinterface_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_networkinterface_info.py\", line 305, in exec_module
  File \"/tmp/ansible_azure_rm_networkinterface_info_payload_98gpx7ge/ansible_azure_rm_networkinterface_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_networkinterface_info.py\", line 322, in get_item
  File \"/tmp/ansible_azure_rm_networkinterface_info_payload_98gpx7ge/ansible_azure_rm_networkinterface_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 1052, in network_client
  File \"/tmp/ansible_azure_rm_networkinterface_info_payload_98gpx7ge/ansible_azure_rm_networkinterface_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 920, in get_mgmt_svc_client
TypeError: __init__() got an unexpected keyword argument 'credential'
```

**Comment by Fred-sun** [comment]
@ToxicGLaDOS Thank you for reporting this problem, could you please help check your azure-mgmt-network version? Because it has been upgraded. Thank you very much!
```e.g.
azure-mgmt-network==19.1.0
azure-identity==1.7.0

**Comment by ToxicGLaDOS** [comment]
@Fred-sun It looks like we're pretty far behind 
```
bash-4.4# pip freeze | grep 'azure-mgmt-network\|azure-identity'
azure-identity==1.7.0
azure-mgmt-network==12.0.0
```

**Comment by Fred-sun** [comment]
@ToxicGLaDOS Please upgrade ”azure-mgmt-network==19.1.0" . Thanks!

**Comment by nicolaibaralmueller** [comment]
I had to re-install all python modules on the virt python env with the latest requirements

[https://raw.githubusercontent.com/ansible-collections/azure/v1.12.0/requirements-azure.txt](url)

Only updating azure-mgmt-network was not enough.

**Comment by sparampalli** [comment]
We also ran into a similar issue with the Ansible module - azure.azcollection.azure_rm_deployment. After updating the packages as per requirements-azure.txt, there is seems to a new issue. This issue particularly happens while creating Azure Cloud stack with RM template having linuxconfig which installs a rpm package like NGINX/Apache2 etc.

Error on Azure while running the linuxconfig is "NGINX package is not found". In the Linux config I am doing the pkg update followed by installing NGINX. 

This works fine in 1.90 - 1.11.0.

**Collection version**
azure.azcollection            1.12.0

**Error**
{
  "changed": false,
  "failed_deployment_operations": [
    {
      "id": "/subscriptions/0eebbbed-14c0-462e-99e0-dfec1d42e0c9/resourceGroups/SaaS-T1-ResourceGroup/providers/Microsoft.Resources/deployments/SaaS-T1/operations/E6E81D82BE994FBB",
      "operation_id": "E6E81D82BE994FBB",
      "provisioning_state": "Failed",
      "status_code": "Conflict",
      "status_message": {
        "error": {
          "code": "ResourceDeploymentFailure",
          "details": [
            {
              "code": "VMExtensionProvisioningError",
              "message": "VM has reported a failure when processing extension 'linuxconfig'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=100\n[stdout]\n InRelease [114 kB]\nGet:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]\nGet:5 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [1347 kB]\nGet:6 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [970 kB]\nGet:7 http://archive.ubuntu.com/ubuntu focal/main Translation-en [506 kB]\nGet:8 http://archive.ubuntu.com/ubuntu focal/main amd64 c-n-f Metadata [29.5 kB]\nGet:9 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [22.0 kB]\nGet:10 http://archive.ubuntu.com/ubuntu focal/restricted Translation-en [6212 B]\nGet:11 http://archive.ubuntu.com/ubuntu focal/restricted amd64 c-n-f Metadata [392 B]\nGet:12 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [8628 kB]\nGet:13 http://security.ubuntu.com/ubuntu focal-security/main Translation-en [234 kB]\nGet:14 http://security.ubuntu.com/ubuntu focal-security/main amd64 c-n-f Metadata [9800 B]\nGet:15 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [831 kB]\nGet:16 http://security.ubuntu.com/ubuntu focal-security/restricted Translation-en [118 kB]\nGet:17 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 c-n-f Metadata [532 B]\nGet:18 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [695 kB]\nGet:19 http://security.ubuntu.com/ubuntu focal-security/universe Translation-en [122 kB]\nGet:20 http://security.ubuntu.com/ubuntu focal-security/universe amd64 c-n-f Metadata [14.1 kB]\nGet:21 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [20.7 kB]\nGet:22 http://security.ubuntu.com/ubuntu focal-security/multiverse Translation-en [5196 B]\nGet:23 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 c-n-f Metadata [500 B]\nGet:24 http://archive.ubuntu.com/ubuntu focal/universe Translation-en [5124 kB]\nGet:25 http://archive.ubuntu.com/ubuntu focal/universe amd64 c-n-f Metadata [265 kB]\nGet:26 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [144 kB]\nGet:27 http://archive.ubuntu.com/ubuntu focal/multiverse Translation-en [104 kB]\nGet:28 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 c-n-f Metadata [9136 B]\nGet:29 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1674 kB]\nGet:30 http://archive.ubuntu.com/ubuntu focal-updates/main Translation-en [316 kB]\nGet:31 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 c-n-f Metadata [14.9 kB]\nGet:32 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [887 kB]\nGet:33 http://archive.ubuntu.com/ubuntu focal-updates/restricted Translation-en [127 kB]\nGet:34 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 c-n-f Metadata [528 B]\nGet:35 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [913 kB]\nGet:36 http://archive.ubuntu.com/ubuntu focal-updates/universe Translation-en [203 kB]\nGet:37 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 c-n-f Metadata [20.3 kB]\nGet:38 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [24.4 kB]\nGet:39 http://archive.ubuntu.com/ubuntu focal-updates/multiverse Translation-en [7336 B]\nGet:40 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 c-n-f Metadata [592 B]\nGet:41 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [42.2 kB]\nGet:42 http://archive.ubuntu.com/ubuntu focal-backports/main Translation-en [10.1 kB]\nGet:43 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 c-n-f Metadata [864 B]\nGet:44 http://archive.ubuntu.com/ubuntu focal-backports/restricted amd64 c-n-f Metadata [116 B]\nGet:45 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [22.7 kB]\nGet:46 http://archive.ubuntu.com/ubuntu focal-backports/universe Translation-en [15.4 kB]\nGet:47 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 c-n-f Metadata [804 B]\nGet:48 http://archive.ubuntu.com/ubuntu focal-backports/multiverse amd64 c-n-f Metadata [116 B]\nFetched 24.1 MB in 6s (3711 kB/s)\nReading package lists...\nReading package lists...\nBuilding dependency tree...\nReading state information...\n\n[stderr]\nE: Unable to locate package nginx\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "
            }
          ],
          "message": "The resource operation completed with terminal provisioning state 'Failed'."
        },
        "status": "Failed"
      },
      "target_resource": {
        "id": "/subscriptions/0eebbbed-14c0-462e-99e0-dfec1d42e0c9/resourceGroups/SaaS-T1-ResourceGroup/providers/Microsoft.Compute/virtualMachines/SaaS-T1-VM/extensions/linuxconfig",
        "resource_name": "SaaS-T1-VM/linuxconfig",
        "resource_type": "Microsoft.Compute/virtualMachines/extensions"
      }
    },
    {
      "id": "/subscriptions/0eebbbed-14c0-462e-99e0-dfec1d42e0c9/resourceGroups/SaaS-T1-ResourceGroup/providers/Microsoft.Resources/deployments/SaaS-T1/operations/08585531533912086862",
      "operation_id": "08585531533912086862",
      "provisioning_state": "Failed",
      "status_code": "Conflict",
      "status_message": "Template output evaluation skipped: at least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
      "target_resource": null
    }
  ],
  "msg": "Deployment failed: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details."
}

**Step on Error**
This issue particularly happens while creating Azure Cloud stack with RM template having linuxconfig which installs a rpm package like NGINX/Apache2 etc.

Error on Azure while running the linuxconfig is "NGINX package is not found". In the Linux config I am doing the pkg update followed by installing NGINX.

**Steps to reproduce**
For a Ubuntu VM, below part of code is added as LinuxConfig.
- comments: Installs NGNIX
          type: Microsoft.Compute/virtualMachines/extensions
          name: "[concat(parameters('vmName'),'/linuxconfig')]"
          apiVersion: '2015-06-15'
          location: "[parameters('location')]"
          dependsOn:
            - "[parameters('vmName')]"
          properties:
            publisher: Microsoft.Azure.Extensions
            type: CustomScript
            typeHandlerVersion: '2.1'
            autoUpgradeMinorVersion: true
            settings:
              commandToExecute: sudo rm -rf /var/lib/apt/lists/* && sudo apt-get update -y && sudo apt-get install nginx -y && sudo /etc/init.d/nginx start

**Comment by Fred-sun** [comment]
@sparampalli Thank you for putting forward the problem you have encountered, and I suggest you resubmit an Issue, so that it is easy to track and solve. Thank you very much!

**Comment by Fred-sun** [comment]
Since this problem is not a bug, I will close it. Thank you very much!
