### ISSUE TITLE
azure_rm_keyvault_info failed with TypeError: __init__() missing 1 required positional argument: 'credential'

### ISSUE THREAD

**Issue by ghost** [ansible/ansible_collections_azure#503]
##### SUMMARY

When collecting info with
```yaml
- name: get available key_vault in resource group
      azure.azcollection.azure_rm_keyvault_info:
        resource_group: rg-weu-dev
      register: keyvault_fact
```
receive a failed message

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure.azcollection.azure_rm_keyvault_info

##### ANSIBLE VERSION

```paste below
ansible 2.9.0
  config file = $HOME/projects/work/project-name/ansible.cfg
  configured module search path = ['$HOME/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = $HOME/projects/work/project-name/.venv/lib/python3.7/site-packages/ansible
  executable location = $HOME/projects/work/project-name/.venv/bin/ansible
  python version = 3.7.8 (default, Sep 17 2020, 13:33:03) [Clang 11.0.3 (clang-1103.0.32.62)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING($HOME/projects/work/project-name/ansible.cfg) = True
ANSIBLE_SSH_CONTROL_PATH($HOME/projects/work/project-name/ansible.cfg) = /tmp/ansible-ssh-%%h-%%p-%%r
COLOR_CHANGED($HOME/projects/work/project-name/ansible.cfg) = yellow
COLOR_DEBUG($HOME/projects/work/project-name/ansible.cfg) = dark gray
COLOR_DEPRECATE($HOME/projects/work/project-name/ansible.cfg) = purple
COLOR_DIFF_ADD($HOME/projects/work/project-name/ansible.cfg) = green
COLOR_DIFF_LINES($HOME/projects/work/project-name/ansible.cfg) = cyan
COLOR_DIFF_REMOVE($HOME/projects/work/project-name/ansible.cfg) = red
COLOR_ERROR($HOME/projects/work/project-name/ansible.cfg) = red
COLOR_HIGHLIGHT($HOME/projects/work/project-name/ansible.cfg) = white
COLOR_OK($HOME/projects/work/project-name/ansible.cfg) = green
COLOR_SKIP($HOME/projects/work/project-name/ansible.cfg) = cyan
COLOR_UNREACHABLE($HOME/projects/work/project-name/ansible.cfg) = red
COLOR_VERBOSE($HOME/projects/work/project-name/ansible.cfg) = blue
COLOR_WARN($HOME/projects/work/project-name/ansible.cfg) = bright purple
DEFAULT_CALLBACK_WHITELIST($HOME/projects/work/project-name/ansible.cfg) = ['profile_tasks']
DEFAULT_EXECUTABLE($HOME/projects/work/project-name/ansible.cfg) = /bin/bash
DEFAULT_FORKS($HOME/projects/work/project-name/ansible.cfg) = 500
DEFAULT_GATHER_SUBSET($HOME/projects/work/project-name/ansible.cfg) = ['all']
DEFAULT_HASH_BEHAVIOUR($HOME/projects/work/project-name/ansible.cfg) = merge
DEFAULT_HOST_LIST(/$HOME/projects/work/project-name/ansible.cfg) = ['$HOME/projects/work/project-name/inventories']
DEFAULT_ROLES_PATH($HOME/projects/work/project-name/ansible.cfg) = ['$HOME/projects/work/project-name/roles']
DEFAULT_STDOUT_CALLBACK($HOME/projects/work/project-name/ansible.cfg) = debug
DEFAULT_TIMEOUT($HOME/projects/work/project-name/ansible.cfg) = 60
DEFAULT_TRANSPORT($HOME/projects/work/project-name/ansible.cfg) = smart
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = $HOME/.ansible/vault_pass
DISPLAY_ARGS_TO_STDOUT($HOME/projects/work/project-name/ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS($HOME/projects/work/project-name/ansible.cfg) = True
HOST_KEY_CHECKING($HOME/projects/work/project-name/ansible.cfg) = False
INVENTORY_ENABLED($HOME/projects/work/project-name/ansible.cfg) = ['ini', 'azure.azcollection.azure_rm']
RETRY_FILES_ENABLED($HOME/projects/work/project-name/ansible.cfg) = False

```

##### OS / ENVIRONMENT

CentOS7, CentOS8, macOS 10.14

##### STEPS TO REPRODUCE

```yaml
- name: dynamic variables assignment
  hosts: localhost
  connection: local
  become: false
  gather_facts: yes
  tasks:
    - name: get available key_vault in resource group
      azure.azcollection.azure_rm_keyvault_info:
        resource_group: rg-weu-dev
      register: keyvault_fact

    - name: keyvault debug
      debug:
        msg: "{{ keyvault_fact }}"
```

##### EXPECTED RESULTS

Prints a dict returned from a keyvault_fact

##### ACTUAL RESULTS

```paste below
TASK [get available key_vault in resource group] ***********************************************************************************************************************************************************************************************************************************************************************
task path: $HOME/projects/work/project-name/playbook.yml:13
Tuesday 20 April 2021  14:50:45 +0200 (0:00:01.493)       0:00:02.568 ********* 
Using module file $HOME/.ansible/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvault_info.py
Pipelining is enabled.
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: lebedeva
<127.0.0.1> EXEC /bin/bash -c '$HOME/projects/work/project-name/.venv/bin/python && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "$HOME/.pyenv/versions/3.7.8/lib/python3.7/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "$HOME/.pyenv/versions/3.7.8/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/folders/2n/ky8cfwpj67jdz1mx02bqgns80000gn/T/ansible_azure.azcollection.azure_rm_keyvault_info_payload_m75omy81/ansible_azure.azcollection.azure_rm_keyvault_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvault_info.py", line 329, in <module>
  File "/var/folders/2n/ky8cfwpj67jdz1mx02bqgns80000gn/T/ansible_azure.azcollection.azure_rm_keyvault_info_payload_m75omy81/ansible_azure.azcollection.azure_rm_keyvault_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvault_info.py", line 325, in main
  File "/var/folders/2n/ky8cfwpj67jdz1mx02bqgns80000gn/T/ansible_azure.azcollection.azure_rm_keyvault_info_payload_m75omy81/ansible_azure.azcollection.azure_rm_keyvault_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvault_info.py", line 235, in __init__
  File "/var/folders/2n/ky8cfwpj67jdz1mx02bqgns80000gn/T/ansible_azure.azcollection.azure_rm_keyvault_info_payload_m75omy81/ansible_azure.azcollection.azure_rm_keyvault_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 453, in __init__
  File "/var/folders/2n/ky8cfwpj67jdz1mx02bqgns80000gn/T/ansible_azure.azcollection.azure_rm_keyvault_info_payload_m75omy81/ansible_azure.azcollection.azure_rm_keyvault_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvault_info.py", line 246, in exec_module
  File "/var/folders/2n/ky8cfwpj67jdz1mx02bqgns80000gn/T/ansible_azure.azcollection.azure_rm_keyvault_info_payload_m75omy81/ansible_azure.azcollection.azure_rm_keyvault_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 898, in get_mgmt_svc_client
TypeError: __init__() missing 1 required positional argument: 'credential'

fatal: [localhost]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "$HOME/.pyenv/versions/3.7.8/lib/python3.7/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "$HOME/.pyenv/versions/3.7.8/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/folders/2n/ky8cfwpj67jdz1mx02bqgns80000gn/T/ansible_azure.azcollection.azure_rm_keyvault_info_payload_m75omy81/ansible_azure.azcollection.azure_rm_keyvault_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvault_info.py", line 329, in <module>
  File "/var/folders/2n/ky8cfwpj67jdz1mx02bqgns80000gn/T/ansible_azure.azcollection.azure_rm_keyvault_info_payload_m75omy81/ansible_azure.azcollection.azure_rm_keyvault_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvault_info.py", line 325, in main
  File "/var/folders/2n/ky8cfwpj67jdz1mx02bqgns80000gn/T/ansible_azure.azcollection.azure_rm_keyvault_info_payload_m75omy81/ansible_azure.azcollection.azure_rm_keyvault_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvault_info.py", line 235, in __init__
  File "/var/folders/2n/ky8cfwpj67jdz1mx02bqgns80000gn/T/ansible_azure.azcollection.azure_rm_keyvault_info_payload_m75omy81/ansible_azure.azcollection.azure_rm_keyvault_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 453, in __init__
  File "/var/folders/2n/ky8cfwpj67jdz1mx02bqgns80000gn/T/ansible_azure.azcollection.azure_rm_keyvault_info_payload_m75omy81/ansible_azure.azcollection.azure_rm_keyvault_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvault_info.py", line 246, in exec_module
  File "/var/folders/2n/ky8cfwpj67jdz1mx02bqgns80000gn/T/ansible_azure.azcollection.azure_rm_keyvault_info_payload_m75omy81/ansible_azure.azcollection.azure_rm_keyvault_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 898, in get_mgmt_svc_client
TypeError: __init__() missing 1 required positional argument: 'credential'
```

**Comment by praveenghuge** [comment]
@anatolylebedev-tomtom you might have the latest version for azure-mgmt-keyvault, for ansible-azure currently the latest version needs some changes, can you please try using azure-mgmt-keyvault==2.2.0 which should work.

**Comment by ghost** [comment]
@praveenghuge after updating to 2.2.0 the issue stands:

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Your credentials class does not support session injection. Performance will not be at the maximum.
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/Users/lebedeva/.pyenv/versions/3.7.8/lib/python3.7/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/Users/lebedeva/.pyenv/versions/3.7.8/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/folders/2n/ky8cfwpj67jdz1mx02bqgns80000gn/T/ansible_azure.azcollection.azure_rm_keyvaultsecret_info_payload_0q1y1lwl/ansible_azure.azcollection.azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret_info.py", line 430, in <module>
  File "/var/folders/2n/ky8cfwpj67jdz1mx02bqgns80000gn/T/ansible_azure.azcollection.azure_rm_keyvaultsecret_info_payload_0q1y1lwl/ansible_azure.azcollection.azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret_info.py", line 426, in main
  File "/var/folders/2n/ky8cfwpj67jdz1mx02bqgns80000gn/T/ansible_azure.azcollection.azure_rm_keyvaultsecret_info_payload_0q1y1lwl/ansible_azure.azcollection.azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret_info.py", line 239, in __init__
  File "/var/folders/2n/ky8cfwpj67jdz1mx02bqgns80000gn/T/ansible_azure.azcollection.azure_rm_keyvaultsecret_info_payload_0q1y1lwl/ansible_azure.azcollection.azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 453, in __init__
  File "/var/folders/2n/ky8cfwpj67jdz1mx02bqgns80000gn/T/ansible_azure.azcollection.azure_rm_keyvaultsecret_info_payload_0q1y1lwl/ansible_azure.azcollection.azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret_info.py", line 262, in exec_module
  File "/var/folders/2n/ky8cfwpj67jdz1mx02bqgns80000gn/T/ansible_azure.azcollection.azure_rm_keyvaultsecret_info_payload_0q1y1lwl/ansible_azure.azcollection.azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret_info.py", line 368, in list_secrets
  File "/Users/lebedeva/projects/work/historic-traffic-ansible/.venv/lib/python3.7/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/Users/lebedeva/projects/work/historic-traffic-ansible/.venv/lib/python3.7/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/Users/lebedeva/projects/work/historic-traffic-ansible/.venv/lib/python3.7/site-packages/azure/keyvault/key_vault_client.py", line 1868, in internal_paging
    request, header_parameters, **operation_config)
  File "/Users/lebedeva/projects/work/historic-traffic-ansible/.venv/lib/python3.7/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/Users/lebedeva/projects/work/historic-traffic-ansible/.venv/lib/python3.7/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/Users/lebedeva/projects/work/historic-traffic-ansible/.venv/lib/python3.7/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/Users/lebedeva/projects/work/historic-traffic-ansible/.venv/lib/python3.7/site-packages/msrest/pipeline/requests.py", line 72, in send
    return self.next.send(request, **kwargs)
  File "/Users/lebedeva/projects/work/historic-traffic-ansible/.venv/lib/python3.7/site-packages/msrest/pipeline/requests.py", line 137, in send
    return self.next.send(request, **kwargs)
  File "/Users/lebedeva/projects/work/historic-traffic-ansible/.venv/lib/python3.7/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/Users/lebedeva/projects/work/historic-traffic-ansible/.venv/lib/python3.7/site-packages/msrest/pipeline/requests.py", line 193, in send
    self.driver.send(request.http_request, **kwargs)
  File "/Users/lebedeva/projects/work/historic-traffic-ansible/.venv/lib/python3.7/site-packages/msrest/universal_http/requests.py", line 333, in send
    return super(RequestsHTTPSender, self).send(request, **requests_kwargs)
  File "/Users/lebedeva/projects/work/historic-traffic-ansible/.venv/lib/python3.7/site-packages/msrest/universal_http/requests.py", line 142, in send
    **kwargs)
  File "/Users/lebedeva/projects/work/historic-traffic-ansible/.venv/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/lebedeva/projects/work/historic-traffic-ansible/.venv/lib/python3.7/site-packages/requests/sessions.py", line 662, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/Users/lebedeva/projects/work/historic-traffic-ansible/.venv/lib/python3.7/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/Users/lebedeva/projects/work/historic-traffic-ansible/.venv/lib/python3.7/site-packages/azure/keyvault/custom/key_vault_authentication.py", line 146, in _handle_401
    security = self._get_message_security(prep, challenge)
  File "/Users/lebedeva/projects/work/historic-traffic-ansible/.venv/lib/python3.7/site-packages/azure/keyvault/custom/key_vault_authentication.py", line 172, in _get_message_security
    scheme))
  File "/Users/lebedeva/projects/work/historic-traffic-ansible/.venv/lib/python3.7/site-packages/azure/keyvault/custom/key_vault_authentication.py", line 61, in _auth_callback_compat
    if len(inspect.getargspec(self._user_callback).args) == 3 \
  File "/var/folders/2n/ky8cfwpj67jdz1mx02bqgns80000gn/T/ansible_azure.azcollection.azure_rm_keyvaultsecret_info_payload_0q1y1lwl/ansible_azure.azcollection.azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret_info.py", line 279, in auth_callback
KeyError: 'client_id'
```

**Comment by Fred-sun** [comment]
@anatolylebedev-tomtom Could you please try this version？ "azure -mgmt-keyvault==1.1.0" is the version required by ansible-collection! Thank you very much! 
[https://github.com/ansible-collections/azure/blob/dev/requirements-azure.txt](url)

**Comment by ghost** [comment]
@Fred-sun it fails to collect an info as initial message said

**Comment by Fred-sun** [comment]
@anatolylebedev-tomtom Can you help to provide the output results? Thank you very much!

**Comment by Fred-sun** [comment]
@anatolylebedev-tomtom Since I haven't encountered any of the problems you mentioned while copying locally, I suggest you upgrade ansible and ansible_collections and reinstall the dependency packages, thanks!

```e.g.
sudo pip3 install ansible[azure] --upgrade
sudo ansible-galaxy collection install azure.azcollection --force

**Comment by Fred-sun** [comment]
@anatolylebedev-tomtom It should be your credential permissions problem, or account problem. I have not had any problems with the latest version of Azure Collection and if there are no other problems, I will close it. Thank you very much!
```e.g.
ansible-galaxy collection install azure.azcollection --force
```
```e.g.
        "secrets": [
            {
                "attributes": {
                    "created": "2021-07-01T01:16:55+00:00",
                    "enabled": true,
                    "expires": null,
                    "not_before": null,
                    "recovery_level": "Recoverable+Purgeable",
                    "updated": "2021-07-01T01:16:55+00:00"
                },
                "content_type": "Content Type Secret",
                "secret": "mysecret",
                "sid": "https://xxx/secrets/testsecret/xxxx",
                "tags": {
                    "delete": "on-exit",
                    "testing": "test"
                },
                "version": "eca8f76e4bd0451ab114805f0d7eb7f8"
            }
        ]

**Comment by ghost** [comment]
@Fred-sun please close it I do not have time and environment right now to try to reproduce this issue. As soon as I will have this again I'll reopen this one or open a new.
Thanks a lot and sorry for bothering you.
