### PR TITLE
Test fix: Drop retired unmanaged-disk Import path & bump AKS public IP prefix

### PR DESCRIPTION
**Pull request by zunyangc**
##### SUMMARY
1. The `azure_rm_snapshot` integration [test](https://dev.azure.com/azclitools/internal/_build/results?buildId=326290&view=logs&j=b6daf38b-8237-596a-54bf-319fae9744cb&t=4d624bf0-640b-531f-6c03-5be4c6767d72&l=3434) started failing on ADO after #2288 was merged:
```
Error while resolving value for 'creation_data':
object of type 'dict' has no attribute 'storage_account_name'
```
The test's gen1 VM is now provisioned as a managed-disk VM, so `azure_rm_virtualmachine_info` no longer returns `storage_account_name` / `storage_container_name` / `storage_blob_name` (those keys are only populated for unmanaged VHD OS disks — see `plugins/modules/azure_rm_virtualmachine_info.py:593-598`). Templating `vm_output.vms[0].storage_account_name` in the "Import from blob" snapshot task therefore fails.

2. The `Create a new agent pool with multi parameters` task also [fails](https://dev.azure.com/azclitools/internal/_build/results?buildId=326290&view=logs&j=87662bd3-73e9-5512-140a-881cf3a08334&t=03624cb0-ae0b-50ac-be66-fb25944bc2b0&l=3279) on ADO with:
```
(PublicIpPrefixOutOfIpAddressesForVMScaleSet) Public IP prefix '<...>/29'
has 8 available IPs but the node pool requires 10.
```
The test's public-IP prefix is `/29` (8 usable IPs), but agent pool `default06` has `enable_auto_scaling: true` with `max_count: 10`. Azure validates prefix capacity against `max_count`, not `count`, so 8 < 10, fail.

##### ISSUE TYPE
- Test Fix Pull Request

##### COMPONENT NAME
tests/integration/targets/azure_rm_snapshot/tasks/main.yml
tests/integration/targets/azure_rm_aksagentpool

##### ADDITIONAL INFORMATION
- Remove the "Import from blob" snapshot task and its assertion.
- Remove the dead scaffolding it depended on (vnet, subnet, NIC, gen1 VM, `Get VM facts`, VM cleanup).
- Enrich the surviving `Copy` snapshot task with `sku` and `os_type` (previously uncovered parameters).
- Add a real idempotency check (re-run the same Copy task, assert `output is not changed`) and fix the misnamed existing assertion that claimed to check idempotency but actually asserted `is changed`.
- Bump `prefix_length` from 29 to 28 (16 usable IPs), giving headroom for the existing `max_count: 10` and any future bumps.

### CODE REVIEW

**Comment by zunyangc** [comment]
Hi @Vieran, pipeline tests passed:
- [azure_rm_snapshot](https://dev.azure.com/azclitools/internal/_build/results?buildId=326342&view=logs&j=b6daf38b-8237-596a-54bf-319fae9744cb&t=4d624bf0-640b-531f-6c03-5be4c6767d72)
- [azure_rm_aksagentpool](https://dev.azure.com/azclitools/internal/_build/results?buildId=326341&view=logs&j=87662bd3-73e9-5512-140a-881cf3a08334&t=03624cb0-ae0b-50ac-be66-fb25944bc2b0)

Ready to merge, thanks!

**Review by Vieran — APPROVED** [review]
