### ISSUE TITLE
azure_rm_account_info dont work since v2

### ISSUE THREAD

**Issue by ebuildy** [ansible/ansible_collections_azure#1413]
##### SUMMARY

task:

```
    - name: Get facts for current logged in user
      azure.azcollection.azure_rm_account_info:
      register: azure_account
```

throw error  **The error was: TypeError: Session.request() got an unexpected keyword argument 'claims'**

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.2]
  config file = None
  configured module search path = ['/Users/tdecaux/.ansible/venv2/amsible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tdecaux/.ansible/venv2/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/tdecaux/.ansible/venv2/amsible/collections:/usr/share/ansible/collections
  executable location = /Users/tdecaux/.ansible/venv2/bin/ansible
  python version = 3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)] (/Users/tdecaux/.ansible/venv2/bin/python3.11)
  jinja version = 3.1.3
  libyaml = True
```

##### COLLECTION VERSION

v2 (work with v1.19.0)

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
python3 -m venv ~/.ansible/venv2
source ~/.ansible/venv2/bin/activate

ansible-galaxy collection install azure.azcollection # version 2
# install azcollection 
pip install -r requirements-azure.tx
```

##### ACTUAL RESULTS

throw error  **The error was: TypeError: Session.request() got an unexpected keyword argument 'claims'**

```
  File "/var/folders/l0/4hldrgzs74s5wgjtnscj5k2m0000gq/T/ansible_azure.azcollection.azure_rm_account_info_payload_rjeoflfh/ansible_azure.azcollection.azure_rm_account_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_account_info.py", line 204, in getAccount
  File "/Users/tdecaux/.ansible/venv2/lib/python3.11/site-packages/msgraph/generated/users/item/user_item_request_builder.py", line 156, in get
    return await self.request_adapter.send_async(request_info, User, error_mapping)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tdecaux/.ansible/venv2/lib/python3.11/site-packages/kiota_http/httpx_request_adapter.py", line 178, in send_async
    response = await self.get_http_response_message(request_info, parent_span)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tdecaux/.ansible/venv2/lib/python3.11/site-packages/kiota_http/httpx_request_adapter.py", line 521, in get_http_response_message
    await self._authentication_provider.authenticate_request(
  File "/Users/tdecaux/.ansible/venv2/lib/python3.11/site-packages/kiota_abstractions/authentication/base_bearer_token_authentication_provider.py", line 50, in authenticate_request
    token = await self.access_token_provider.get_authorization_token(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tdecaux/.ansible/venv2/lib/python3.11/site-packages/kiota_authentication_azure/azure_identity_access_token_provider.py", line 103, in get_authorization_token
    result = self._credentials.get_token(*self._scopes, claims=decoded_claim)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tdecaux/.ansible/venv2/lib/python3.11/site-packages/azure/cli/core/auth/credential_adaptor.py", line 65, in get_token
    token, _ = self._get_token(scopes, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tdecaux/.ansible/venv2/lib/python3.11/site-packages/azure/cli/core/auth/credential_adaptor.py", line 38, in _get_token
    token = self._credential.get_token(*scopes, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tdecaux/.ansible/venv2/lib/python3.11/site-packages/azure/cli/core/auth/msal_authentication.py", line 60, in get_token
    result = self.acquire_token_silent_with_error(list(scopes), self._account, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tdecaux/.ansible/venv2/lib/python3.11/site-packages/msal/application.py", line 1269, in acquire_token_silent_with_error
    return _clean_up(self._acquire_token_silent_with_error(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tdecaux/.ansible/venv2/lib/python3.11/site-packages/msal/application.py", line 1292, in _acquire_token_silent_with_error
    result = self._acquire_token_silent_from_cache_and_possibly_refresh_it(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tdecaux/.ansible/venv2/lib/python3.11/site-packages/msal/application.py", line 1422, in _acquire_token_silent_from_cache_and_possibly_refresh_it
    result = self._acquire_token_silent_by_finding_rt_belongs_to_me_or_my_family(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tdecaux/.ansible/venv2/lib/python3.11/site-packages/msal/application.py", line 1483, in _acquire_token_silent_by_finding_rt_belongs_to_me_or_my_family
    last_resp = at = self._acquire_token_silent_by_finding_specific_refresh_token(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tdecaux/.ansible/venv2/lib/python3.11/site-packages/msal/application.py", line 1533, in _acquire_token_silent_by_finding_specific_refresh_token
    response = client.obtain_token_by_refresh_token(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tdecaux/.ansible/venv2/lib/python3.11/site-packages/msal/oauth2cli/oauth2.py", line 830, in obtain_token_by_refresh_token
    resp = super(Client, self).obtain_token_by_refresh_token(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tdecaux/.ansible/venv2/lib/python3.11/site-packages/msal/oauth2cli/oauth2.py", line 262, in obtain_token_by_refresh_token
    return self._obtain_token("refresh_token", data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tdecaux/.ansible/venv2/lib/python3.11/site-packages/msal/oauth2cli/oidc.py", line 116, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tdecaux/.ansible/venv2/lib/python3.11/site-packages/msal/oauth2cli/oauth2.py", line 771, in _obtain_token
    resp = super(Client, self)._obtain_token(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tdecaux/.ansible/venv2/lib/python3.11/site-packages/msal/oauth2cli/oauth2.py", line 234, in _obtain_token
    resp = (post or self._http_client.post)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tdecaux/.ansible/venv2/lib/python3.11/site-packages/msal/individual_cache.py", line 269, in wrapper
    value = function(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tdecaux/.ansible/venv2/lib/python3.11/site-packages/msal/individual_cache.py", line 269, in wrapper
    value = function(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tdecaux/.ansible/venv2/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Session.request() got an unexpected keyword argument 'claims'
```

#####  Related

https://github.com/ansible-collections/azure/issues/1387

**Comment by radsto** [comment]
Bump

**Comment by Fred-sun** [comment]
@ebuildy @radsto azure_rm_account_info.py is used to access login account information, so when using this module, you need to have az login, and then use the cli credentials(auth_source: cli) to get login account information through the 'auth_source' setting. After migrating to msgraph earlier, you need to make a few minor changes, see https://github.com/ansible-collections/azure/pull/1510.。 Thank you!

    - name: Get account facts
      azure.azcollection.azure_rm_account_info:
        auth_source: cli
      register: output
    - debug:
        var: output

Return:
"output": {
        "account_info": {
            "environmentName": "AzureCloud",
            "homeTenantId": "xxxxxxxxxx",
            "id": "xxxxxxxxxxxxxxxxxxxxxxxxx",
            "managedByTenants": [],
            "name": "Visual Studio Enterprise",
            "state": "Enabled",
            "tenantId": "8xxxxxxxxxxxxxxxxxxxxxxx",
            "user": {
                "name": "xxxxxxxxxxxxxxxxxx",
                "type": "Member"
            }
        },

**Comment by Fred-sun** [comment]
Fixed by #1510

**Comment by radsto** [comment]
Thanks for the workaround, I will test this !

**Comment by Fred-sun** [comment]
> Thanks for the workaround, I will test this !

Any feedback?

**Comment by radsto** [comment]
@Fred-sun

I have cloned your branch with the fix and ran the following playbook

```yaml
- hosts: localhost
  tasks:
    - name: Get facts for current logged in user
      azure.azcollection.azure_rm_account_info:
        auth_source: cli
      register: azure_account

    - debug:
        var: azure_account
```

It passes fine :

![image](https://github.com/ansible-collections/azure/assets/94012491/307d9a8b-a511-46aa-a067-7010da635efe)

Thanks for your fix and wish you a nice day !

**Comment by Fred-sun** [comment]
@ebuildy @radsto The related PR has been merged and I will close this issue. Thank you!
